name: Build and Test

on:
  push:
    branches: [ upstream-dev ]
  pull_request:
    branches: [ upstream-dev ]

jobs:
  win_build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
        working-directory: tools
    env:
      PROJECT: swmm
      BUILD_HOME: build
      TEST_HOME: nrtests
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-win.txt
    - name: Build and unit test
      run: make.cmd /g "Visual Studio 16 2019" /t
    - name: Build
      run: make.cmd /g "Visual Studio 16 2019"
    - name: Before test
      run: before-nrtest.cmd
    - name: Reg test
      run: run-nrtests.cmd
    - uses: edgarrc/action-7z@v1.0.4
      with:
        args: 7z a benchmark-%PLATFORM%-%SUT_BUILD_ID%.zip %TEST_HOME%\benchmark\swmm-%SUT_BUILD_ID% 
