name: Build and Test

on:
  push:
    branches: [ upstream-dev ]
  pull_request:
    branches: [ upstream-dev ]

jobs:
  win_build:
    runs-on: windows-2016
    defaults:
      run:
        shell: cmd
        working-directory: tools
    env:
      PROJECT: swmm
      BUILD_HOME: build
      TEST_HOME: nrtests
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-win.txt
#    - name: Build and unit test
#      run: make.cmd /t
    - name: Build
      run: make.cmd
    - name: Before test
      run: before-nrtest.cmd
    - name: Reg test
      run: run-nrtests.cmd %GITHUB_SHA% %GITHUB_RUN_ID%_%GITHUB_RUN_NUMBER%
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: receipt
        path: $HOME/$BUILD_HOME/benchmark/receipt.json  

      
