name: Build Docs

on:
  push:
    branches: [ master, develop, release, docs ]
  pull_request:
    branches: [ master, develop, release, docs ]

env:
  OMP_NUM_THREADS: 1
    
jobs:
  build_docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Doxygen and Graphviz
        run:
          sudo apt-get install doxygen graphviz -y

      - name: Build Docs
        run: |
          cd docs
          doxygen Doxyfile

      - name: Upload Docs
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/html

