name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  win_build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
        working-directory: tools
    env:
      PROJECT: swmm
      BUILD_HOME: build
      PLATFORM: win64
      TEST_HOME: nrtests
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make.cmd /g "Visual Studio 16 2019"
    - name: before-test
      run: |
        before-nrtest.cmd
        echo ::set-env name=REF_BUILD_ID::%REF_BUILD_ID%
    - name: run-test
      run: run-nrtests.cmd  
